#!/bin/bash
set -e

configure() {
	if ! dpkg-divert --list | grep -q /usr/bin/flatpak; then
		if [ -e "/usr/bin/flatpak.real" ]; then
			rm -f "/usr/bin/flatpak.real"
		fi

		dpkg-divert \
			--rename \
			--package flatpak-hybris \
			--divert "/usr/bin/flatpak.real" \
			--add "/usr/bin/flatpak"
		ln -sf "/usr/lib/flatpak-hybris/flatpak-hybris.sh" "/usr/bin/flatpak"
	fi

	if ! dpkg-divert --list | grep -q /usr/bin/bwrap; then
		if [ -e "/usr/bin/bwrap.real" ]; then
			rm -f "/usr/bin/bwrap.real"
		fi

		dpkg-divert \
			--rename \
			--package flatpak-hybris \
			--divert "/usr/bin/bwrap.real" \
			--add "/usr/bin/bwrap"
		ln -sf "/usr/lib/flatpak-hybris/bwrapwrapper.sh" "/usr/bin/bwrap"
	fi

	# remove setuid bits
	[ -e "/usr/bin/bwrap" ] && chmod u-s /usr/bin/bwrap
	[ -e "/usr/bin/bwrap.real" ] && chmod u-s /usr/bin/bwrap.real

	# remove dpkg statoverride forcing setuid
	if dpkg-statoverride --list /usr/bin/bwrap &> /dev/null; then
		dpkg-statoverride --quiet --remove /usr/bin/bwrap
	fi
}

case "$1" in
	"configure")
		configure
		;;
esac
