#!/bin/bash
set -e

remove() {
	if [ -e "/usr/bin/flatpak.real" ]; then
		rm -f "/usr/bin/flatpak"
		dpkg-divert \
			--rename \
			--package flatpak-hybris \
			--divert "/usr/bin/flatpak.real" \
			--remove "/usr/bin/flatpak"
	fi

	if dpkg-statoverride --list /usr/bin/bwrap &> /dev/null; then
		dpkg-statoverride --quiet --remove /usr/bin/bwrap
	fi
}

case "$1" in
	"remove")
		remove
		;;
esac
